'use strict';
(() => {
  const D=window.LagoonStory,$=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d',{alpha:false}),mini=$('mini'),mctx=mini.getContext('2d');
  const W=D.width,H=D.height,KEY='axolotl-story-v3';
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,coarse=matchMedia('(pointer: coarse)').matches;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
  const image=src=>{const im=new Image();im.src=src;return im;};
  const art={forest:image('reed-forest.png'),cave:image('limestone-cave.png'),axo:image('axo-natural.png'),fish:image('creatures.png')};
  let width=1280,height=720,scale=1,viewW=1280,viewH=1000,last=0,clock=0,accumulator=0,ready=false;
  let mode='menu',region=0,progress=[0,0,0,0,0,0],unlocked=0,party=[],journal=[],picked=[],puzzle={},search={},snacks=0,playTime=0,introSeen=false,completed=false,ending=null;
  let player={x:430,y:1000,vx:0,vy:0,face:1,tilt:0,turn:1,phase:0,stroke:0},camera={x:750,y:950},companions=[];
  let keys=new Set(),joy={x:0,y:0},joyPointer=null,foods=[],schools=[],particles=[],rings=[],currentTarget=null,guide=false;
  let dialogue=null,panelReturn='playing',resting=null,captionUntil=0,bannerUntil=0,saveClock=0,audioClock=0,sound=false,audio=null,master=null,saved=null,assetCrop={x:0,y:0,w:1760,h:880},smallFish=null;
  let storageWarning=false,largeMap=null;
  function resize(){width=canvas.clientWidth||innerWidth;height=canvas.clientHeight||innerHeight;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;scale=height/viewH;viewW=width/scale;ctx.setTransform(dpr,0,0,dpr,0,0);if(['playing','dialogue','panel'].includes(mode)){boundCamera();setGameUI(true);}}
  new ResizeObserver(resize).observe(canvas);resize();
  function boundCamera(){camera.x=clamp(camera.x,Math.min(viewW/2,W/2),Math.max(W-viewW/2,W/2));camera.y=clamp(camera.y,viewH/2,H-viewH/2);}
  function validateSave(s){if(!s||s.version!==3||!Number.isInteger(s.region)||s.region<0||s.region>5||!Array.isArray(s.progress)||s.progress.length!==6||s.progress.some(p=>!Number.isInteger(p)||p<0||p>4))return null;return {...s,unlocked:clamp(Number(s.unlocked)||0,0,5),party:Array.isArray(s.party)?s.party.filter(n=>['Ada','Mira','Nara'].includes(n)).slice(0,3):[],journal:Array.isArray(s.journal)?s.journal.filter(e=>e&&typeof e.id==='string'&&Array.isArray(e.pages)).slice(0,35):[],picked:Array.isArray(s.picked)?s.picked.filter(v=>typeof v==='string').slice(0,180):[],puzzle:s.puzzle&&typeof s.puzzle==='object'?s.puzzle:{},search:s.search&&typeof s.search==='object'?s.search:{},snacks:clamp(Number(s.snacks)||0,0,9),playTime:Math.max(0,Number(s.playTime)||0),position:{x:clamp(Number(s.position?.x)||430,130,W-130),y:clamp(Number(s.position?.y)||1000,180,H-160)}};}
  try{saved=validateSave(JSON.parse(localStorage.getItem(KEY)));}catch{}
  function snapshot(){return {version:3,region,progress:[...progress],unlocked,party:[...party],journal,picked,puzzle,search,snacks,playTime,introSeen,completed,ending,position:{x:player.x,y:player.y}};}
  function save(){if(!introSeen&&mode==='menu')return;try{const s=snapshot();localStorage.setItem(KEY,JSON.stringify(s));saved=s;$('continue').hidden=false;$('continue').textContent='Devam et · '+D.regions[region].name;$('new-game').textContent='Yeni bir yolculuk';$('saved-label').textContent='Yolculuk kaydedildi';}catch{if(!storageWarning){storageWarning=true;caption('Bu tarayıcı ilerlemeyi kaydedemiyor. Sayfayı açık tutarak devam edebilirsin.');}$('saved-label').textContent='Kayıt bu tarayıcıda kullanılamıyor';}}
  function clearInput(){keys.clear();joy={x:0,y:0};joyPointer=null;resting=null;$('interaction').querySelector('.hold-track').hidden=true;$('stick').style.transform='translate(0px,0px)';}
  function setGameUI(on){$('hud').hidden=!on;$('compass-wrap').hidden=!on;$('mini-wrap').hidden=!on;$('desktop-hint').hidden=!on;$('journal-button').hidden=!on;$('map-button').hidden=!on;$('pause-button').hidden=!on;$('touch').hidden=!(on&&mode==='playing'&&(coarse||width<700));}
  function caption(text){$('caption').textContent=text;$('caption').style.opacity='1';captionUntil=clock+4.5;}
  function banner(){const r=D.regions[region];$('banner-small').textContent='BÖLÜM '+(region+1)+' / 6 · '+r.subtitle.toLocaleUpperCase('tr-TR');$('banner-title').textContent=r.name;$('chapter-banner').style.opacity='1';bannerUntil=clock+4.5;}
  function tone(frequency,duration=1,volume=.02){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();if(!master){master=audio.createGain();master.connect(audio.destination);}master.gain.value=.55;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=frequency;gain.gain.setValueAtTime(.001,audio.currentTime);gain.gain.linearRampToValueAtTime(volume,audio.currentTime+.12);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain);gain.connect(master);osc.start();osc.stop(audio.currentTime+duration+.05);}catch{}}
  function seed(n){const v=Math.sin(n*127.1+region*83.7)*43758.5453;return v-Math.floor(v);}
  function buildWorld(){
    foods=Array.from({length:27},(_,i)=>({id:region+'-food-'+i,x:i<9?720+seed(i+10)*1050:450+seed(i+10)*(W-900),y:440+seed(i+95)*950,phase:seed(i+51)*6,alive:!picked.includes(region+'-food-'+i)}));
    schools=Array.from({length:30},(_,i)=>({x:250+seed(i+360)*(W-500),y:240+seed(i+580)*(H-450),vx:(seed(i+150)-.5)*25,vy:0,phase:seed(i+75)*7,size:18+seed(i+121)*18}));
    companions=party.map((name,i)=>({name,x:player.x-(i+1)*90,y:player.y+(i%2?25:-25),vx:0,vy:0,face:1,phase:i}));particles=[];rings=[];currentTarget=null;boundCamera();updateHUD();
  }
  function start(resume=false){if(!ready)throw new Error('Görseller henüz hazır değil');clearInput();
    if(resume&&saved){const s=validateSave(saved);if(!s)throw new Error('Kayıt okunamadı');region=s.region;progress=[...s.progress];unlocked=s.unlocked;party=[...s.party];journal=[...s.journal];picked=[...s.picked];puzzle={...s.puzzle};search={...s.search};snacks=s.snacks;playTime=s.playTime;introSeen=!!s.introSeen;completed=!!s.completed;ending=s.ending??null;player={x:s.position.x,y:s.position.y,vx:0,vy:0,face:1,tilt:0,turn:1,phase:0,stroke:0};}
    else{if(saved){try{localStorage.setItem(KEY+'-previous',JSON.stringify(saved));}catch{}}region=0;progress=[0,0,0,0,0,0];unlocked=0;party=[];journal=[];picked=[];puzzle={};search={};snacks=0;playTime=0;introSeen=false;completed=false;ending=null;player={x:430,y:1000,vx:0,vy:0,face:1,tilt:0,turn:1,phase:0,stroke:0};}
    mode='playing';camera={x:player.x,y:player.y};$('menu').hidden=true;$('panel').hidden=true;$('dialogue').hidden=true;dialogue=null;buildWorld();setGameUI(true);banner();saveClock=0;canvas.focus({preventScroll:true});
    if(!introSeen)openDialogue(D.opening,()=>{introSeen=true;save();caption(coarse||width<700?'Sol kontrolle yüz; birine yaklaşınca DİNLE düğmesini kullan.':'WASD ile yüz. Ulu’ya yaklaşıp E ile konuş.');});else caption('Kaldığın kıyıdan, kendi hızında devam et.');
  }
  function remember(entry){if(!journal.some(e=>e.id===entry.id))journal.push({id:entry.id,title:entry.title||entry.heading,speaker:entry.speaker,pages:[...entry.pages],region});}
  function openDialogue(entry,after){mode='dialogue';clearInput();player.vx=0;player.vy=0;dialogue={entry,index:0,after};remember(entry);$('dialogue').hidden=false;$('panel').hidden=true;$('interaction').hidden=true;$('touch').hidden=true;$('chapter-banner').style.opacity='0';showPage();$('dialogue-next').focus({preventScroll:true});}
  function showPage(){if(!dialogue)return;const e=dialogue.entry;$('speaker').textContent=e.speaker;$('dialogue-title').textContent=e.title||e.heading;$('dialogue-text').textContent=e.pages[dialogue.index];$('page-count').textContent=(dialogue.index+1)+' / '+e.pages.length;const choosing=e.choice&&dialogue.index===e.pages.length-1;$('story-choices').hidden=!choosing;$('dialogue-next').hidden=!!choosing;$('dialogue-next').textContent=dialogue.index<e.pages.length-1?'Dinlemeye devam et ›':'Yola devam et ›';}
  function advanceDialogue(){if(mode!=='dialogue'||!dialogue)return false;if(dialogue.entry.choice&&dialogue.index===dialogue.entry.pages.length-1)return false;if(dialogue.index<dialogue.entry.pages.length-1){dialogue.index++;showPage();}else{const after=dialogue.after;dialogue=null;mode='playing';$('dialogue').hidden=true;setGameUI(true);after?.();updateHUD();save();if(mode==='playing')canvas.focus({preventScroll:true});}return true;}
  function activeStage(){return D.regions[region].stages[progress[region]]??null;}
  function stageKey(){return region+'-'+progress[region];}
  function puzzleNodes(){return [{id:0,name:'Damlacık',x:1780,y:660,size:16},{id:1,name:'Sızıntı',x:2360,y:1170,size:25},{id:2,name:'Dere',x:2930,y:720,size:36}];}
  function memoryNodes(){return [{id:0,name:'Yaprağın biriktiği oyuk',x:2200,y:650},{id:1,name:'Kumun biriktiği oyuk',x:2760,y:1250},{id:2,name:'Kabuğun biriktiği oyuk',x:3350,y:750}];}
  function targets(){const s=activeStage();if(!s)return [{x:4080,y:900,type:'exit',label:completed?'Diğer kıyıları ziyaret et':'Bir sonraki kıyıya geç'}];if(s.type==='puzzle')return puzzleNodes().map(n=>({...n,type:'puzzle',label:n.name+' kaynağını aç'}));if(s.type==='search')return memoryNodes().filter(n=>!(search[stageKey()]||[]).includes(n.id)).map(n=>({...n,type:'memory',label:n.name}));return [{x:s.x,y:s.y,type:s.type,label:s.type==='rest'?'Dur ve suyu dinle':s.type==='feed'?D.regions[region].npc+' ile paylaş':s.type==='escort'?'Dostunla havuza ulaş':s.title}];}
  function completeStage(){const s=activeStage();if(!s)return;const old=progress[region];progress[region]++;if(D.regions[region].friend&&old=== (D.regions[region].friend==='Mira'?2:1)){const name=D.regions[region].friend;if(!party.includes(name)){party.push(name);companions.push({name,x:player.x-70,y:player.y+20,vx:0,vy:0,face:player.face,phase:party.length});}}tone(330,.9,.025);save();updateHUD();if(progress[region]===4&&!completed)caption('Bu kıyının yolu açıldı. Doğudaki açıklığa yüz.');}
  function stageDialogue(s,after=completeStage){openDialogue({...s,id:stageKey()},after);}
  function interact(){if(mode!=='playing')return false;const available=targets().filter(t=>distance(t,player)<140);available.sort((a,b)=>distance(a,player)-distance(b,player));const t=available[0];if(!t){rings.push({x:player.x,y:player.y,r:30,life:2});guide=true;$('guide-button').setAttribute('aria-pressed','true');caption('Suyun taşıdığı iz, bir sonraki durağını gösteriyor.');return false;}const s=activeStage();
    if(t.type==='exit'){if(region<5&&!completed){region++;unlocked=Math.max(unlocked,region);player.x=430;player.y=1000;player.vx=0;player.vy=0;camera={x:player.x,y:player.y};buildWorld();banner();save();}else openPanel('map');return true;}
    if(s.type==='feed'){if(snacks<3){caption('Paylaşmak için '+(3-snacks)+' küçük lokma daha bul. Köklerin çevresindeki soluk noktaları takip et.');guide=true;return false;}snacks-=3;stageDialogue(s);return true;}
    if(s.type==='escort'){const companion=companions.find(c=>c.name===D.regions[region].friend);if(companion&&distance(companion,t)>210+companions.indexOf(companion)*90){caption('Dostun yaklaşırken biraz bekle.');return false;}stageDialogue(s);return true;}
    if(s.type==='rest'){if(resting)return false;resting={x:t.x,y:t.y,elapsed:0};caption('Hareket etmeden birkaç saniye kal. Suyun sesini dinle.');$('interaction').querySelector('.hold-track').hidden=false;return true;}
    if(s.type==='puzzle'){const key=stageKey(),step=Number(puzzle[key])||0;if(t.id<step){caption('Bu kaynak diğer kola bağlandı.');return false;}if(t.id!==step){caption('Önce damlacık, sonra sızıntı, en son dere. Küçük halkadan başla.');return false;}puzzle[key]=step+1;rings.push({x:t.x,y:t.y,r:10,life:3});tone([220,277,330][step],1.4,.025);if(step===2)stageDialogue(s);else{caption(t.name+' açıldı. Su sıradaki kola ulaşıyor.');save();}return true;}
    if(s.type==='search'){const key=stageKey(),found=search[key]||[],notes=[['Yaprak','Sazların arasından kopmuş ince bir yaprak, taşın oyuk yüzeyine takılmış. Uzun bir yolu sessizce geçmiş. Üzerindeki açık çizgiyi evimizin köklerinden tanıyorum. Buraya gelen su, bizim kıyımızdan da geçmiş olmalı.'],['Kum','Açık renkli kum, koyu taşın içinde ince bir çizgi oluşturmuş. Su çekilse bile çizgi kalıyor. Mira, ana kaynağın yatağında aynı kumu gördüğünü hatırlıyor. Taşlar yolu kapatsa da su geçtiği yeri unutmamış.'],['Kabuk','Kabuğun kenarı aşınmış ama beyazlığı duruyor. Ada onu hemen tanıyor. Nara’nın bulduğu parça bunun diğer yarısı olabilir. Bir kabuğun iki parçası, iki uzak kıyıda aynı yolun izini tutmuş.']];openDialogue({id:key+'-memory-'+t.id,title:notes[t.id][0],speaker:'Axo',pages:[notes[t.id][1]]},()=>{if(!found.includes(t.id))found.push(t.id);search[key]=found;save();if(found.length===3)stageDialogue(s);else caption('İncelenen iz: '+found.length+' / 3');});return true;}
    if(s.type==='ending'){stageDialogue({...s,choice:true},()=>{});return true;}
    stageDialogue(s);return true;
  }
  function chooseEnding(choice){if(!['water','friends'].includes(choice)||mode!=='dialogue'||!dialogue?.entry.choice)throw new Error('Geçersiz hatıra seçimi');ending=choice;openDialogue({id:'ending-'+choice,speaker:'Axo',title:choice==='water'?'Suyun sesi':'Dört gölge',pages:D.endings[choice]},()=>{progress[5]=4;completed=true;save();openPanel('ending');});}
  function stroke(){if(mode!=='playing'||player.stroke>0)return;let dx=joy.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=joy.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(!dx&&!dy)dx=player.face;const l=Math.hypot(dx,dy);player.vx+=dx/l*105;player.vy+=dy/l*105;player.stroke=1.8;player.phase+=.6;resting=null;$('interaction').querySelector('.hold-track').hidden=true;}
  function flowAt(x,y){const power=D.regions[region].flow,phase=region*.7;let vx=power*.5+Math.sin(y*.006+phase)*power*.3,vy=Math.sin(x*.003+phase)*power*.18;if(region===3){const ox=x-2450,oy=y-930,f=Math.exp(-(ox*ox/900000+oy*oy/300000));vx+=-oy*.065*f;vy+=ox*.035*f;}if(region===5&&progress[5]>=2)vx+=12;return {vx,vy};}
  function update(dt){playTime+=dt;saveClock+=dt;player.stroke=Math.max(0,player.stroke-dt);let dx=joy.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=joy.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);const l=Math.hypot(dx,dy);if(l>1){dx/=l;dy/=l;}const flow=flowAt(player.x,player.y);
    if(resting&&(Math.abs(dx)+Math.abs(dy)>.1)){resting=null;$('interaction').querySelector('.hold-track').hidden=true;}
    if(resting){player.vx*=Math.exp(-dt*5);player.vy*=Math.exp(-dt*5);player.x=lerp(player.x,resting.x,1-Math.exp(-dt*2));player.y=lerp(player.y,resting.y,1-Math.exp(-dt*2));resting.elapsed+=dt;$('hold-progress').style.width=clamp(resting.elapsed/4,0,1)*100+'%';if(resting.elapsed>=4){resting=null;$('interaction').querySelector('.hold-track').hidden=true;stageDialogue(activeStage());return;}}
    else{const thrust=285,drag=1.9;player.vx+=(dx*thrust+(flow.vx-player.vx)*drag)*dt;player.vy+=(dy*thrust+(flow.vy-player.vy)*drag-.8)*dt;const speed=Math.hypot(player.vx,player.vy);if(speed>230){player.vx*=230/speed;player.vy*=230/speed;}player.x+=player.vx*dt;player.y+=player.vy*dt;}
    const floor=H-140-Math.sin(player.x*.003)*24,ceiling=150+Math.sin(player.x*.002)*25;
    if(player.x<130||player.x>W-130){player.x=clamp(player.x,130,W-130);player.vx*=.2;}if(player.y<ceiling||player.y>floor){player.y=clamp(player.y,ceiling,floor);player.vy*=.2;}
    if(Math.abs(player.vx)>20)player.face=player.vx>0?1:-1;player.turn=lerp(player.turn,player.face,1-Math.exp(-dt*6));player.tilt=lerp(player.tilt,clamp(player.vy/(Math.abs(player.vx)+90),-.45,.45)*player.face,1-Math.exp(-dt*3));player.phase+=dt*(1.7+Math.hypot(player.vx-flow.vx,player.vy-flow.vy)*.017);
    camera.x=lerp(camera.x,player.x+player.vx*.38,1-Math.exp(-dt*2.3));camera.y=lerp(camera.y,player.y+player.vy*.25,1-Math.exp(-dt*2.3));camera.x=clamp(camera.x,Math.min(viewW/2,W/2),Math.max(W-viewW/2,W/2));camera.y=clamp(camera.y,viewH/2,H-viewH/2);
    if(activeStage()?.type==='feed'){foods.forEach(f=>{if(f.alive&&snacks<9&&distance(f,player)<34){f.alive=false;picked.push(f.id);snacks++;tone(440,.35,.012);caption('Küçük lokma · '+Math.min(snacks,3)+' / 3');save();}});}
    companions.forEach((c,i)=>{const ahead=i?companions[i-1]:player,tx=ahead.x-player.face*(78+i*7),ty=ahead.y+(i%2?23:-23),response=1-Math.exp(-dt*2.1);c.vx=(tx-c.x)*1.8;c.vy=(ty-c.y)*1.8;c.x=lerp(c.x,tx,response);c.y=lerp(c.y,ty,response);if(Math.abs(c.vx)>8)c.face=c.vx>0?1:-1;c.phase+=dt*(1.3+Math.hypot(c.vx,c.vy)*.012);});
    const ts=targets();currentTarget=ts.filter(t=>distance(t,player)<140).sort((a,b)=>distance(a,player)-distance(b,player))[0]||null;updateInteraction();if(saveClock>8){saveClock=0;save();}
  }
  function updateInteraction(){$('interaction').hidden=!currentTarget||mode!=='playing';if(currentTarget)$('interaction-label').textContent=currentTarget.label;}
  function updateHUD(){const s=activeStage(),r=D.regions[region];$('chapter-label').textContent='0'+(region+1)+' / 06 · '+r.name.toLocaleUpperCase('tr-TR');$('objective').textContent=completed?'Lagün artık tanıdık.':s?s.title:'Bir sonraki kıyıya yüz';let detail=s?'Acele etmeden keşfet. Yaklaşınca dinle ve incele.':'Doğudaki açıklık yeni su yoluna açılıyor.';if(s?.type==='feed')detail='Küçük lokmalar: '+Math.min(snacks,3)+' / 3 · soluk noktaların yanından yüz.';if(s?.type==='puzzle')detail='Açılan kaynaklar: '+(puzzle[stageKey()]||0)+' / 3 · damlacık, sızıntı, dere.';if(s?.type==='search')detail='İncelenen oyuklar: '+(search[stageKey()]||[]).length+' / 3';if(s?.type==='escort')detail='Dostunla birlikte ilerle; havuza vardığında onu bekle.';if(s?.type==='rest')detail='Taşa yaklaş, dinlemeyi seç; hareket etmeden kısa bir süre kal.';if(completed)detail='Günlükteki haritadan keşfettiğin kıyılara dönebilirsin.';$('objective-detail').textContent=detail;$('chapter-progress').innerHTML=[0,1,2,3].map(i=>'<i class="'+(i<progress[region]?'done':i===progress[region]?'current':'')+'"></i>').join('');$('mini-region').textContent=r.name.toLocaleUpperCase('tr-TR');}
  function closePanel(){if(mode!=='panel')return;mode=panelReturn;$('panel').hidden=true;if(mode==='dialogue'){$('dialogue').hidden=false;$('dialogue-next').focus({preventScroll:true});}else{setGameUI(true);canvas.focus({preventScroll:true});}}
  function openPanel(kind){if(mode==='menu')return;panelReturn=mode==='panel'?panelReturn:mode;mode='panel';clearInput();$('panel').hidden=false;$('dialogue').hidden=true;$('touch').hidden=true;$('interaction').hidden=true;const content=$('panel-content');content.innerHTML='';$('pause-actions').hidden=true;largeMap=null;
    if(kind==='pause'){$('panel-kicker').textContent='MOLA';$('panel-title').textContent='Su burada kalır.';$('panel-copy').textContent='Yolculuğun bu tarayıcıda kaydedilir. Hazır olduğunda kaldığın yerden devam edebilirsin.';$('pause-actions').hidden=false;save();}
    if(kind==='journal'){$('panel-kicker').textContent='KEŞİF GÜNLÜĞÜ';$('panel-title').textContent='Yol boyunca hatırladıkların.';$('panel-copy').textContent=journal.length+' hatıra · '+party.length+' yol arkadaşı. Konuşmalarını burada yeniden okuyabilirsin.';for(const entry of journal){const details=document.createElement('details');details.className='entry';const summary=document.createElement('summary');summary.textContent=entry.title;details.appendChild(summary);const small=document.createElement('small');small.textContent=entry.speaker+' · '+D.regions[clamp(entry.region??0,0,5)].name;details.appendChild(small);entry.pages.forEach(text=>{const p=document.createElement('p');p.textContent=text;details.appendChild(p);});content.appendChild(details);}}
    if(kind==='map'){$('panel-kicker').textContent='LAGÜNÜN KIYILARI';$('panel-title').textContent='Bildiğin yollara dönebilirsin.';$('panel-copy').textContent='İlerlemen korunur. Keşfettiğin bir kıyıya dönmek için adını seç.';const tabs=document.createElement('div');tabs.className='region-tabs';D.regions.forEach((r,i)=>{const b=document.createElement('button');b.textContent=(i+1)+' · '+r.name;b.disabled=i>unlocked;b.setAttribute('aria-current',String(i===region));b.onclick=()=>visitRegion(i);tabs.appendChild(b);});content.appendChild(tabs);largeMap=document.createElement('canvas');largeMap.width=880;largeMap.height=370;largeMap.className='large-map';largeMap.setAttribute('aria-label','Bölge, akıntılar, duraklar ve konumun');content.appendChild(largeMap);const p=document.createElement('p');p.className='map-legend';p.textContent='Açık halka: sıradaki durak · küçük noktalar: yiyecek · dolu halka: tamamlanan durak · çizgiler: suyun akış yönü';content.appendChild(p);drawMap(largeMap.getContext('2d'),880,370);}
    if(kind==='ending'){panelReturn='playing';$('panel-kicker').textContent='ALTI KIYI, TEK YOL';$('panel-title').textContent='Yolculuk biter. Lagün kalır.';$('panel-copy').textContent='Üç dostun yanında. Suyun yolu yeniden açık. Hatıran günlüğe yazıldı; artık tüm kıyıları kendi hızında ziyaret edebilirsin.';const b=document.createElement('button');b.className='primary';b.textContent='Lagünü keşfetmeye devam et';b.onclick=closePanel;content.appendChild(b);}
    $('panel-close').focus({preventScroll:true});
  }
  function visitRegion(index){if(!Number.isInteger(index)||index<0||index>unlocked)throw new Error('Bu kıyı henüz keşfedilmedi');region=index;player.x=430;player.y=1000;player.vx=0;player.vy=0;camera={x:player.x,y:player.y};dialogue=null;panelReturn='playing';closePanel();buildWorld();banner();save();}
  function home(){save();clearInput();mode='menu';dialogue=null;$('dialogue').hidden=true;$('panel').hidden=true;$('menu').hidden=false;$('interaction').hidden=true;$('chapter-banner').style.opacity='0';$('caption').style.opacity='0';setGameUI(false);}
  function pause(){if(mode==='panel')closePanel();else if(mode==='playing'||mode==='dialogue')openPanel('pause');}
  function prepareArt(){try{const buffer=document.createElement('canvas');buffer.width=art.axo.naturalWidth;buffer.height=art.axo.naturalHeight;const b=buffer.getContext('2d');b.drawImage(art.axo,0,0);const data=b.getImageData(0,0,buffer.width,buffer.height).data;let x0=buffer.width,y0=buffer.height,x1=0,y1=0;for(let y=0;y<buffer.height;y+=3)for(let x=0;x<buffer.width;x+=3)if(data[(y*buffer.width+x)*4+3]>40){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}if(x1>x0&&y1>y0)assetCrop={x:x0,y:y0,w:x1-x0+3,h:y1-y0+3};}catch{}
    try{smallFish=document.createElement('canvas');smallFish.width=120;smallFish.height=86;const b=smallFish.getContext('2d');b.filter='grayscale(.8) brightness(.8)';b.drawImage(art.fish,635,95,615,490,0,0,120,86);}catch{smallFish=null;}
  }
  function drawAxo(p,size=150,alpha=1){if(!art.axo.complete||!art.axo.naturalWidth)return;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.tilt||0);const turn=p.turn??p.face;ctx.scale((turn<0?-1:1)*Math.max(.35,Math.abs(turn)),1);ctx.globalAlpha=alpha;const c=assetCrop,displayH=size*c.h/c.w,segments=24,sw=c.w/segments,dw=size/segments;for(let i=0;i<segments;i++){const fraction=i/segments,tail=Math.max(0,1-fraction/.66),wave=reduced?0:Math.sin((p.phase||clock*1.7)-fraction*5)*tail*tail*4.5;ctx.drawImage(art.axo,c.x+i*sw,c.y,Math.min(sw+2,c.w-i*sw),c.h,-size/2+i*dw,-displayH/2+wave,dw+.45,displayH);}ctx.restore();}
  function visible(p,margin=120){return Math.abs(p.x-camera.x)<viewW/2+margin&&Math.abs(p.y-camera.y)<viewH/2+margin;}
  function drawRing(x,y,r,color='#d9ddad',opacity=.4){ctx.save();ctx.globalAlpha=opacity;ctx.strokeStyle=color;ctx.lineWidth=1.2;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.stroke();ctx.restore();}
  function worldLabel(x,y,text,color='#dde4c9'){ctx.save();ctx.font='12px "Nunito Sans",sans-serif';ctx.textAlign='center';ctx.fillStyle=color;ctx.shadowColor='#082d36';ctx.shadowBlur=8;ctx.fillText(text,x,y);ctx.restore();}
  function drawWorld(){
    ctx.fillStyle='#0b2d35';ctx.fillRect(0,0,width,height);const menu=mode==='menu',r=D.regions[region],bg=menu?art.forest:art[r.art];
    if(menu){if(bg.complete&&bg.naturalWidth){const s=Math.max(width/bg.naturalWidth,height/bg.naturalHeight)*1.03;ctx.drawImage(bg,(width-bg.naturalWidth*s)/2+(reduced?0:Math.sin(clock*.04)*6),(height-bg.naturalHeight*s)/2,bg.naturalWidth*s,bg.naturalHeight*s);}ctx.fillStyle='#16373a19';ctx.fillRect(0,0,width,height);drawAxo({x:width*.76,y:height*(width<700?.81:.58)+(reduced?0:Math.sin(clock*.65)*4),turn:1,tilt:0,phase:clock*1.1},Math.min(340,width*.3),.87);return;}
    ctx.save();ctx.translate(width/2,height/2);ctx.scale(scale,scale);ctx.translate(-camera.x,-camera.y);
    if(bg.complete&&bg.naturalWidth)ctx.drawImage(bg,0,0,W,H);ctx.fillStyle=r.grade;ctx.fillRect(0,0,W,H);
    // Depth haze blends distant scene details; small suspended motes follow the same flow field as the player.
    const haze=ctx.createLinearGradient(0,0,0,H);haze.addColorStop(0,'rgba(124,178,163,.04)');haze.addColorStop(1,'rgba(2,37,49,.2)');ctx.fillStyle=haze;ctx.fillRect(0,0,W,H);
    for(let i=0;i<85;i++){const x=(i*173.71+clock*3)%W,y=(i*127.37+Math.sin(clock*.11+i)*14)%H;if(!visible({x,y},10))continue;ctx.fillStyle=i%4?'#c7dac63a':'#e6eed968';ctx.beginPath();ctx.arc(x,y,.8+i%3*.45,0,Math.PI*2);ctx.fill();}
    schools.forEach(f=>{if(!visible(f,60)||!smallFish)return;ctx.save();ctx.translate(f.x,f.y);ctx.scale(f.vx>0?-1:1,1);ctx.globalAlpha=.55;ctx.rotate(Math.sin(f.phase)*.04);ctx.drawImage(smallFish,-f.size/2,-f.size*.28,f.size,f.size*.7);ctx.restore();});
    if(activeStage()?.type==='feed')foods.forEach(f=>{if(f.alive&&visible(f)){ctx.strokeStyle='#dfdfbf9c';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(f.x-3,f.y);ctx.quadraticCurveTo(f.x,f.y+Math.sin(clock*1.2+f.phase)*2,f.x+4,f.y-2);ctx.stroke();if(guide)drawRing(f.x,f.y,10,'#e2dfb1',.2);}});
    if(!party.includes(r.npc)){drawAxo({x:r.npcAt[0],y:r.npcAt[1]+(reduced?0:Math.sin(clock*.8)*3),turn:-1,phase:clock*1.2},r.npc==='Ulu'?172:126,.9);worldLabel(r.npcAt[0],r.npcAt[1]-50,r.npc);}
    drawLandmarks();
    companions.forEach((c,i)=>{drawAxo({x:c.x,y:c.y,face:c.face,tilt:clamp(c.vy*.002,-.2,.2)*c.face,phase:c.phase},[125,139,113][i]||125,.87);if(guide||mode==='dialogue')worldLabel(c.x,c.y-43,c.name,'#cddbc8');});
    drawAxo(player,156,1);
    rings.forEach(p=>drawRing(p.x,p.y,p.r,'#d2dfc1',p.life/5));
    if(guide)drawGuide();
    ctx.restore();
    if(!reduced){ctx.save();ctx.globalAlpha=.015;ctx.strokeStyle='#d9edc9';ctx.lineWidth=2;for(let i=0;i<5;i++){ctx.beginPath();for(let x=0;x<width+30;x+=30)ctx.lineTo(x,height*.12+i*height*.2+Math.sin(x*.011+clock*.15+i)*17);ctx.stroke();}ctx.restore();}
  }
  function drawLandmarks(){const s=activeStage();if(!s){drawRing(4080,900,75,'#dcebc9',.3);worldLabel(4080,800,completed?'BİLDİĞİN KIYILAR':'SONRAKİ KIYI');return;}
    if(s.type==='puzzle'){const step=Number(puzzle[stageKey()])||0;puzzleNodes().forEach(n=>{if(!visible(n))return;drawRing(n.x,n.y,n.size,'#d7d6aa',n.id<step?.16:.6);drawRing(n.x,n.y,n.size+5,'#e0dec6',.2);worldLabel(n.x,n.y-n.size-16,n.name);if(n.id<step){const next=puzzleNodes()[Math.min(n.id+1,2)];ctx.save();ctx.strokeStyle='#b5d8bf33';ctx.setLineDash([4,13]);ctx.beginPath();ctx.moveTo(n.x,n.y);ctx.quadraticCurveTo((n.x+next.x)/2,(n.y+next.y)/2-90,next.x,next.y);ctx.stroke();ctx.restore();}});}
    else if(s.type==='search'){memoryNodes().forEach(n=>{if(!visible(n))return;const found=(search[stageKey()]||[]).includes(n.id);drawRing(n.x,n.y,30,'#d2debf',found?.1:.5);if(!found&&(guide||distance(n,player)<200))worldLabel(n.x,n.y-50,n.name);});}
    else if(visible(s)){const near=distance(s,player)<220;drawRing(s.x,s.y,s.type==='rest'?58:38,'#dce0b7',near?.55:.23);if(guide||near)worldLabel(s.x,s.y-68,s.type==='rest'?'DİNLENME TAŞI':s.title);}
  }
  function drawGuide(){let candidates=targets();const s=activeStage();if(s?.type==='puzzle')candidates=candidates.filter(n=>n.id===(Number(puzzle[stageKey()])||0));if(s?.type==='feed'&&snacks<3)candidates=foods.filter(f=>f.alive);candidates.sort((a,b)=>distance(a,player)-distance(b,player));const next=candidates[0];if(!next||distance(next,player)<130)return;const angle=Math.atan2(next.y-player.y,next.x-player.x);ctx.save();ctx.translate(player.x+Math.cos(angle)*108,player.y+Math.sin(angle)*108);ctx.rotate(angle);ctx.globalAlpha=.7;ctx.strokeStyle='#e8dfbb';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(-3,-4);ctx.lineTo(4,0);ctx.lineTo(-3,4);ctx.stroke();ctx.restore();}
  function drawMap(c,w,h){c.clearRect(0,0,w,h);c.fillStyle='#0b2b3b';c.fillRect(0,0,w,h);const dot=(x,y,size,color)=>{c.fillStyle=color;c.beginPath();c.arc(x/W*w,y/H*h,size,0,Math.PI*2);c.fill();};c.strokeStyle='#c3d8bb1c';for(let x=400;x<W;x+=500)for(let y=400;y<H;y+=500){const flow=flowAt(x,y);c.beginPath();c.moveTo(x/W*w,y/H*h);c.lineTo((x+flow.vx*5)/W*w,(y+flow.vy*5)/H*h);c.stroke();}D.regions[region].stages.forEach((s,i)=>dot(s.x,s.y,i<progress[region]?2:3,i<progress[region]?'#779987':'#d9dfb7'));targets().forEach(t=>dot(t.x,t.y,3,'#e5d39e'));if(activeStage()?.type==='feed')foods.forEach(f=>{if(f.alive)dot(f.x,f.y,1,'#aebf97');});companions.forEach(f=>dot(f.x,f.y,1.5,'#d8b3b0'));dot(player.x,player.y,4,'#edf2d7');c.strokeStyle='#d6e2c327';c.strokeRect((camera.x-viewW/2)/W*w,(camera.y-viewH/2)/H*h,viewW/W*w,viewH/H*h);}
  function updateEnvironment(dt){schools.forEach((f,i)=>{const near=distance(f,player);let targetX=Math.cos(clock*.06+f.phase)*20,targetY=Math.sin(clock*.09+f.phase)*7;if(mode==='playing'&&near<125){targetX+=(f.x-player.x)/(near||1)*46;targetY+=(f.y-player.y)/(near||1)*35;}const flow=flowAt(f.x,f.y);f.vx=lerp(f.vx,targetX+flow.vx*.3,1-Math.exp(-dt));f.vy=lerp(f.vy,targetY+flow.vy*.3,1-Math.exp(-dt));f.x=clamp(f.x+f.vx*dt,180,W-180);f.y=clamp(f.y+f.vy*dt,180,H-200);f.phase+=dt*2;});rings.forEach(r=>{r.r+=dt*40;r.life-=dt;});rings=rings.filter(r=>r.life>0);}
  let hudTime=0;
  function frame(now){const realDt=Math.min((now-last)/1000||.016,.075);last=now;if(!document.hidden){clock+=realDt;accumulator+=realDt;if(mode==='playing'){while(accumulator>=1/60){update(1/60);accumulator-=1/60;if(mode!=='playing'){accumulator=0;break;}}}else accumulator=0;updateEnvironment(realDt);drawWorld();if(now-hudTime>160){if(mode!=='menu'){updateHUD();drawMap(mctx,160,75);}hudTime=now;}if(captionUntil&&clock>captionUntil){$('caption').style.opacity='0';captionUntil=0;}if(bannerUntil&&clock>bannerUntil){$('chapter-banner').style.opacity='0';bannerUntil=0;}if(sound&&mode!=='menu'&&clock>audioClock){audioClock=clock+3.2;const note=[130.81,146.83,164.81,196,220][Math.floor(clock/6+region)%5];tone(note,3,.015);tone(note*1.5,2.5,.006);}}requestAnimationFrame(frame);}
  function keyboard(e,down){const key=e.key.toLowerCase();if(e.target.tagName==='BUTTON'&&(key===' '||key==='enter'))return;if(!['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e',' ','shift','j','m','p','escape','enter'].includes(key))return;e.preventDefault();if(!down){keys.delete(key);return;}if(mode==='dialogue'){if(['e',' ','enter'].includes(key)&&!e.repeat)advanceDialogue();else if(key==='escape')openPanel('pause');return;}if(mode==='panel'){if(['escape','p'].includes(key)&&!e.repeat)closePanel();return;}if(mode!=='playing')return;if(e.repeat&&['e',' ','shift','j','m','p','escape'].includes(key))return;if(key==='e'||key===' ')interact();else if(key==='shift')stroke();else if(key==='j')openPanel('journal');else if(key==='m')openPanel('map');else if(key==='p'||key==='escape')pause();else keys.add(key);}
  window.addEventListener('keydown',e=>keyboard(e,true));window.addEventListener('keyup',e=>keyboard(e,false));window.addEventListener('blur',()=>{keys.clear();joy={x:0,y:0};if(mode==='playing')openPanel('pause');});document.addEventListener('visibilitychange',()=>{if(document.hidden){save();if(mode==='playing')openPanel('pause');}});
  $('new-game').onclick=()=>start(false);$('continue').onclick=()=>start(true);$('dialogue-next').onclick=advanceDialogue;document.querySelectorAll('[data-ending]').forEach(b=>b.onclick=()=>chooseEnding(b.dataset.ending));$('interact-button').onclick=interact;$('touch-listen').onclick=interact;$('stroke').onpointerdown=e=>{e.preventDefault();stroke();};$('journal-button').onclick=()=>openPanel('journal');$('map-button').onclick=()=>openPanel('map');$('pause-button').onclick=pause;$('panel-close').onclick=closePanel;$('resume').onclick=closePanel;$('home').onclick=home;
  $('guide-button').onclick=()=>{guide=!guide;$('guide-button').setAttribute('aria-pressed',String(guide));};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Ses açık':'Ses kapalı';$('sound').setAttribute('aria-pressed',String(sound));if(sound)tone(196,1.7,.02);else if(master)master.gain.value=0;};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('app').requestFullscreen();}catch{caption('Bu tarayıcıda tam ekran açılamıyor.');}};
  const pad=$('joystick');function moveJoy(e){const r=pad.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,l=Math.hypot(dx,dy),max=32;joy.x=dx/Math.max(max,l);joy.y=dy/Math.max(max,l);$('stick').style.transform='translate('+joy.x*max+'px,'+joy.y*max+'px)';}
  pad.addEventListener('pointerdown',e=>{e.preventDefault();joyPointer=e.pointerId;pad.setPointerCapture(e.pointerId);moveJoy(e);});pad.addEventListener('pointermove',e=>{if(e.pointerId===joyPointer)moveJoy(e);});for(const event of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(event,e=>{if(e.pointerId===joyPointer){joyPointer=null;joy={x:0,y:0};$('stick').style.transform='translate(0px,0px)';}});
  canvas.addEventListener('wheel',e=>{if(mode==='playing'){e.preventDefault();viewH=clamp(viewH+e.deltaY*.3,850,1250);resize();}},{passive:false});
  function loadAssets(){let count=Object.values(art).length;const loaded=()=>{if(--count===0){ready=true;prepareArt();$('new-game').disabled=false;$('continue').disabled=false;$('load-state').textContent='Kendi hızında · Kulaklıkla keşfet';}};$('new-game').disabled=true;$('continue').disabled=true;Object.values(art).forEach(im=>{if(im.complete&&im.naturalWidth)loaded();else{im.onload=loaded;im.onerror=()=>{$('load-state').textContent='Görsel yüklenemedi. Sayfayı yenile.';};}});}
  const state=()=>({mode,region:region+1,regionName:D.regions[region].name,stage:progress[region]+1,objective:activeStage()?.title??'Kıyılar arasında keşif',friends:[...party],journalEntries:journal.length,snacks,completed,ending,playTime:Math.floor(playTime),position:{x:Math.round(player.x),y:Math.round(player.y)},velocity:{x:Math.round(player.vx),y:Math.round(player.vy)},dialogue:dialogue?{title:dialogue.entry.title||dialogue.entry.heading,page:dialogue.index+1,total:dialogue.entry.pages.length}:null,saved:!!saved});
  window.axolotlGame={getState:state,start:options=>start(options?.resume??false),pause,interact,advanceDialogue,chooseEnding};
  if(document.modelContext?.registerTool){const life=new AbortController(),tools=[{name:'read_axolotl_game',description:'Read the calm story adventure status, objective, friends and current dialogue.',annotations:{readOnlyHint:true},inputSchema:{type:'object',properties:{},additionalProperties:false},execute(input={}){if(Object.keys(input).length)throw new Error('No arguments accepted');return state();}},{name:'start_axolotl_game',description:'Start a new story journey or continue the locally saved story. New journeys preserve the previous save as a backup.',annotations:{readOnlyHint:false},inputSchema:{type:'object',properties:{resume:{type:'boolean'}},additionalProperties:false},execute(input={}){if(Object.keys(input).some(k=>k!=='resume')||(input.resume!==undefined&&typeof input.resume!=='boolean'))throw new Error('Invalid input');start(input.resume||false);return state();}},{name:'advance_axolotl_dialogue',description:'Advance the visible story dialogue by one page, completing the encounter after its last page.',annotations:{readOnlyHint:false},inputSchema:{type:'object',properties:{},additionalProperties:false},execute(input={}){if(Object.keys(input).length||mode!=='dialogue')throw new Error('No dialogue available');advanceDialogue();return state();}}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>{if(mode!=='menu')save();life.abort();},{once:true});}
  if(saved){$('continue').hidden=false;$('continue').textContent='Devam et · '+D.regions[saved.region].name;$('new-game').textContent='Yeni bir yolculuk';}
  loadAssets();requestAnimationFrame(frame);
})();
